### ISSUE TITLE
UniFi-Poller: Client Insights - InfluxDB - Clients In Table Not Responding To Time Filter

### ISSUE THREAD

**Issue by ThePieMonster** [unpoller/dashboards#16]
In the v2.0.1 of UniFi-Poller: Client Insights - InfluxDB the dashboard table is not current with the selected time filter. 

For example, the Rx and Tx rates should change when changing the time filter. Seems the data is stuck to looking back over a static period of time.

![image](https://user-images.githubusercontent.com/11359134/147442454-02a98fe2-8758-4f53-8cd3-1af954798ca7.png)

**Comment by davidnewhall** [comment]
I believe it's just showing current. It says right in the corner "Last 5 minutes"
