### ISSUE TITLE
UniFi-Poller: Client Dashboards - Client dashboard variable includes numerous MAC addresses entries

### ISSUE THREAD

**Issue by jhannah01** [unpoller/dashboards#18]
I guess this might be more of a suggestion for an improvement but I know personally my Client dashboard pulldown has a ton of MAC address-only entries at the top of the Client dashboard variable pulldown:
![Client DPI - Client Pulldown](https://user-images.githubusercontent.com/106957/164951441-e83721e3-aa06-4f32-a46c-2668013faa3a.png)
 
Played around with the dashboard variable settings for Client and seems using this value for ``regex`` works to exclude them:
```
    "regex": "/^(?!(?:[a-fA-F0-9]+:)+)(.+)$/",
```

See [this regex101 example](https://regex101.com/r/wTNKIL/1) but I was trying to do a negative look ahead match for any MAC address and otherwise include any positive match.

Best I can tell from looking at the dashboard export JSON model, it seems like the entry for the Client variable has no value for ``regex`` now and setting the above one will result in stripping out all MAC address but that behavior might not be desired.

I feel like there may be a better solution in the form of pulling out MAC addresses conditionally or having another variable that is just MAC addresses but that is about the extent of my knowledge with Grafana dashboards at this point. If it is helpful I can share the full exported dashboard JSON as well.

**Comment by davidnewhall** [comment]
Some client don't have names. I'm not sure hiding them is the right move.
