### ISSUE TITLE
No Data Showing Client DPI 

### ISSUE THREAD

**Issue by lslamp** [unpoller/dashboards#19]
I am very new to grafana and unnifi-poller.
I have installed the unifi-poller on influxdb. I downloaded the following dashboards.

Client DPI 10419  -- shows no data
Sites	10414 -- shows data 
USW	10417 -- shows data
USG	10416  -- shows data
UAP	10415 -- shows data
Clients	10418 -- shows data

As you can see above, all the dashboards work and deliver data very well, only the Client DPI shows no data. 

Below is something that I find strange but don't know how to change/update. As you can see, under the Site selection, there is no site possible, it is showing as None.

![image](https://user-images.githubusercontent.com/6013759/191909826-90c2c991-b3a2-460c-9090-b72c04ab3cd7.png)

![image](https://user-images.githubusercontent.com/6013759/191909445-89defdc5-0e01-4895-b30a-5968cef08142.png)

Is there something I missed in the setup, how can I investigate the no data.

A very BIG Thank You for a great functional product. Very impressive.
Thanks
Lawrence

**Comment by platinummonkey** [comment]
This was fixed I believe in v2.7.10 there as an incorrect type being reported and you may need to drop the series data on client and site dpi measurements
