### ISSUE TITLE
Commas in Client OUI causes misalignment of data by one column

### ISSUE THREAD

**Issue by vidia** [unpoller/dashboards#22]
I'm not sure if the root cause of this issue is in parsing the Unifi data or in the ddashboard itself, but I'm reporting here since its where I see the issue. 

![image](https://user-images.githubusercontent.com/4712072/225055331-2461adc6-7396-4164-8619-109cbad96044.png)

In the screenshot above, the data for my Google Nest Minis is split. It looks like the OUI got split causing everything to be misaligned by one column. Unifi reports the proper OUI is "Google, Inc.", so my gut says this is a CSV parsing issue (or similar) where the `,` isn't being escaped or quoted properly. I get the same issue for other OUI names with commas too, but this is the most obvious. 

Let me know if I can provide any additional info or if there's a better repo to report this issue. Not sure which step in the process caused the problem.  

Happy to dig around for a fix and put together a PR as well if I can get a bit of a head-start from maintainers on where to start looking.

**Comment by vidia** [comment]
As a related (but separate issue), does anyone know why my site_name is reporting as the hostname of my grafana/influx/unpoller install?

**Comment by davidnewhall** [comment]
Looks like Grafana is splitting it. Probably a Grafana bug.

**Comment by platinummonkey** [comment]
Agreed ^ closing as this is out of scope of unpoller

**Comment by davidnewhall** [comment]
(we could `strings.Replace` the commas....)
