### ISSUE TITLE
Add Unpoller to Home Assistant?

### ISSUE THREAD

**Issue by Yzord** [unpoller/dashboards#23]
is it possible to add Unpoller stats to HA? When i try to add InfluxDB to HA it tells me to add a database specific for HA in the yaml file. But i don't know how i can fill this db with Unpoller stats.

**Comment by platinummonkey** [comment]
Move this issue to “unpoller” repo. This repo is focused on grafana dashboards.

**Comment by platinummonkey** [comment]
you might be better off with https://www.home-assistant.io/integrations/prometheus/ today as it should just work out of the box
