### ISSUE TITLE
Last version of Unifi Controller seems to remove SITE from tables

### ISSUE THREAD

**Issue by SVLoneStar** [unpoller/dashboards#25]
I manually had to remove the 'WHERE "site"=/^$site$/' from all graphs in the v2 Dashboards to again see values.

**Comment by amoksworld** [comment]
It seems they changed the database layout, too...

**Comment by vidia** [comment]
From what I can tell, the Site is still set, but it includes (for me at least) a new `(default)` suffix that's causing all the regex matching to break. 

I'm not sure how it ended up being added or when or if that's the cause vs. a change in Grafana parsing, but switching references of `$Site` to `${Site:regex}` seems to solve it.

**Comment by platinummonkey** [comment]
This was fixed with #25
