### ISSUE TITLE
Logspam

### ISSUE THREAD

**Issue by cypherstream** [unpoller/dashboards#28]
Recently upgraded unifi to version 8.0.28 so my unifi-poller stopped working.  Upgraded to unpoller.

Seems to be collecting data OK so far, but this is spamming the logs.  Is this ok?
tail -f -n100  /var/log/syslog /var/log/messages | grep unpoller
tail: cannot open '/var/log/messages' for reading: No such file or directory
Feb  7 04:52:39 grafana unpoller[537983]: 2024/02/07 04:52:39 [ERROR] influxdb.Write(points): {"error":"partial write: field type conflict: input field \"rx_bytes-r\" on measurement \"subsystems\" is type integer, already exists as type float dropped=5"}
Feb  7 04:53:09 grafana unpoller[537983]: 2024/02/07 04:53:09 [ERROR] influxdb.Write(points): {"error":"partial write: field type conflict: input field \"rx_bytes-r\" on measurement \"subsystems\" is type integer, already exists as type float dropped=5"}
Feb  7 04:53:39 grafana unpoller[537983]: 2024/02/07 04:53:39 [ERROR] influxdb.Write(points): {"error":"partial write: field type conflict: input field \"rx_bytes-r\" on measurement \"subsystems\" is type integer, already exists as type float dropped=5"}
Feb  7 04:54:09 grafana unpoller[537983]: 2024/02/07 04:54:09 [ERROR] influxdb.Write(points): {"error":"partial write: field type conflict: input field \"rx_bytes-r\" on measurement \"subsystems\" is type integer, already exists as type float dropped=5"}
Feb  7 04:54:39 grafana unpoller[537983]: 2024/02/07 04:54:39 [ERROR] influxdb.Write(points): {"error":"partial write: field type conflict: input field \"rx_bytes-r\" on measurement \"subsystems\" is type integer, already exists as type float dropped=5"}
Feb  7 04:55:09 grafana unpoller[537983]: 2024/02/07 04:55:09 [ERROR] influxdb.Write(points): {"error":"partial write: field type conflict: input field \"rx_bytes-r\" on measurement \"subsystems\" is type integer, already exists as type float dropped=5"}
Feb  7 04:55:39 grafana unpoller[537983]: 2024/02/07 04:55:39 [ERROR] influxdb.Write(points): {"error":"partial write: field type conflict: input field \"rx_bytes-r\" on measurement \"subsystems\" is type integer, already exists as type float dropped=5"}

**Comment by platinummonkey** [comment]
See https://github.com/unpoller/unpoller/issues/575 you need to wipe the data, this is a specific influx problem and unifi changing the data type
