### ISSUE TITLE
Grafana charts are empty when time interval is small

### ISSUE THREAD

**Issue by outofsight** [unpoller/dashboards#30]
For example USW Insights, Data Transfer chart show no data when time range is 2 days, but if I change the time range to 1 week suddenly the data appear.

It seems something related to a recent change. I run unpoller since 1y and I never noticed this behavior.

Any idea?

Seems related to scaping interval (Mine is set to 30s in Grafana Agent) and minimum interval in dashboard (set to 30s on empty charts and to 2min on others)

**Comment by SuperQ** [comment]
This is more a datasource problem than a chart problem. I configure 15s scrape intervals, which matches the Grafana datasource default for my Prometheus server.

In Grafana (`/connections/datasources`) you can configure the default minimum scrape interval at the datasource level.

![image](https://github.com/unpoller/dashboards/assets/1320667/bac24ef6-d41b-408a-a700-270f43e299bd)

**Comment by SuperQ** [comment]
Oh, I see, it seems like the dashboards are also incorrectly configured with the wrong interval variable.

**Comment by outofsight** [comment]
> Oh, I see, it seems like the dashboards are also incorrectly configured with the wrong interval variable.

exactly, the dashboards were not using the proper variable
