### ISSUE TITLE
Dashboard Dependancy Deprecated 

### ISSUE THREAD

**Issue by lslamp** [unpoller/dashboards#31]
Dear David,

Thank you again for such great dashboards. Only in the last months I have noticed that there seems to be a warning that has popped up after I upgraded Grafana the last time. See image below.  
"Angular plugin 
This plugin uses a deprecated, legacy platform based on AngularJS and will stop working in future releases of Grafana."

![image](https://github.com/unpoller/dashboards/assets/6013759/c88d95e8-2288-450a-a953-607703dd1b5e)

I am a complete novice when it comes to Grafana and the dashboards. How can I resolve this issue.
Is there a fix for this?

Thanks
Lawrence

**Comment by lslamp** [comment]
@chrede88 
Christian, Thank for the pointer. I will try this later and see if it resolved the warning.
Lawrence

**Comment by lslamp** [comment]
@chrede88 
Christian, your suggestion worked for most of the dashboards. 
The issue that I have run into is twofold.
The first issue is that there are many panels that do not show the edit option so I cannot change the pluging. So how can I change the panels without the edit option.
The second issue is that there are like 300 panels still to do, is there a way to do a mass update at all?

Thanks
Lawrence

**Comment by davidnewhall** [comment]
> So how can I change the panels without the edit option.

Those are repeating panels. If you edit the first one, the repeaters will update as well. 

>  is there a way to do a mass update at all?

Everything is possible, but it may not be something you're able to do. 

There are a lot of Grafana tutorials out there; I recommend checking a few out to upgrade your knowledge on this subject.

**Comment by lslamp** [comment]
@davidnewhall 
Thank you for the reply. I did come to realize that the panels that cannot be edited will all update after updating the primary. It only took a little time on my server for some reason.
As for the mass update. I ended up doing it all manually. I also did realize that the Angular thing was a warning but that would be an issue after the next upgrade of grafana. I have now updated all the panels and all is good again.

Lastly, is it possible to get the unifi devices temperature using unpoller?

Thanks
Lawrence

**Comment by davidnewhall** [comment]
> Lastly, is it possible to get the unifi devices temperature using unpoller?

Possible, of course. Might already do it now. Depends on the device.

**Comment by lslamp** [comment]
I have added the following Unifi Home dashboard to Grafana but there are one or two panels that do not work.
He also mentions that the dashboard is utilized in conjunction with Unifi-Poller (I assume that Unpoller and Unifi-poller are one and the same.)
On the dashboard he has a panel that has no data, well two panels that have no data.
The queries linked to the no data are .
1. SELECT last("temp_CPU") FROM "usg" WHERE ("site_name" =~ /^$Site$/ AND "source" =~ /^$Controller$/) AND $timeFilter
this seems related to CPU temperature.
If I use the commandline to query the influxdb and only run the command 
SELECT last("temp_CPU") FROM "usg" 
I get nothing back?
How can I check if there is a column within the usg table for the CPU Temp?

2. SELECT distinct("ip") FROM "usg" WHERE ("site_name" =~ /^$Site$/ AND "source" =~ /^$Controller$/) AND $timeFilter GROUP BY "model", "version"
this seems to be related to ip address and controller version.
If I use the commandline to query the influxdb and only run the command 
SELECT distinct("ip") FROM "usg" 
I am given the local upaddress and the external WAN ipaddress, but if I add only this commend into the query section of the panel I still get no data. Why do I get the ipaddress on the commandline and nothing within the panel?(the panel is a table type)

any ideas?
Thanks
Lawrence

**Comment by lslamp** [comment]
> > So how can I change the panels without the edit option.
> 
> Those are repeating panels. If you edit the first one, the repeaters will update as well.
> 
> > is there a way to do a mass update at all?
> 
> Everything is possible, but it may not be something you're able to do.
> 
> There are a lot of Grafana tutorials out there; I recommend checking a few out to upgrade your knowledge on this subject.
> 
> Lastly, the warning about Angular is just a warning. You can ignore it.

After updating the primary panel, how long should it be before all the other panels get updated?

I am having issues with the USG Gateway panel that I have had to delete and replace, but after updating the primary, the cascading panels don't seem to follow. This was done days ago now.

Lawrence

**Comment by chrede88** [comment]
Bumping this as grafana v11 has now been released. This release marks the end-of-life of AngularJS panels. See docs: https://grafana.com/docs/grafana/latest/breaking-changes/breaking-changes-v11-0/#angularjs-support-is-turned-off-by-default

This is break many of the panels in the provided unpoller dashboards!

**Comment by lslamp** [comment]
This can be closed but if anyone needs feedback. I am happy to help
