### ISSUE TITLE
Add support for gateways of type UXG to USG dashboard

### ISSUE THREAD

**Issue by chrede88** [unpoller/dashboards#33]
The USG dashboard doesn't currently support gateways of type `uxg`. At the time of opening this issue, I believe there are now three such gateways available: `UXG-Lite`, `UXG-Max` and `UXG-Pro`. I got some of the dashboard to work by simply including `uxg` as an option for the defined dashboard variables.

```
label_values(unpoller_device_info{type=~"udm|usg|ugw|uxg"},source)
label_values(unpoller_device_info{source=~"$Controller", type=~"udm|usg|ugw|uxg"},site_name)
label_values(unpoller_device_info{site_name=~"$Site", type=~"udm|usg|ugw|uxg"},name)
```

I'm running a UXG-Max, and can therefore run some tests if that's helpful.

**Comment by platinummonkey** [comment]
Fixed in #41
