### ISSUE TITLE
Added UXG Max Gateway, USG Dashboard shows extra Panels.

### ISSUE THREAD

**Issue by lslamp** [unpoller/dashboards#35]
I have just updated my UXG Lite to the UGX Max Gateway device.
The switch went well, only when I open the UniFi-Poller: USG Insights - InfluxDB Dashboard, I am presented with the following dashoard.
![image](https://github.com/unpoller/unpoller/assets/6013759/665f2942-7cb1-4097-a11a-07cd6c538c3d)
I think that this was caused by me renaming the gateway after the installation.
The current name is ICANGateway. No matter what I try I cannot seem to remove the other two Gateway names.
I did try to delete these but then it also ended up deleting the ICANGateway as well.
Looking at the separate dashboards, two of the 3 have no data. The ICANGateway has data as expected.
How can I delete the second two dashboards. Below are all 3 dashboards.
![image](https://github.com/unpoller/unpoller/assets/6013759/d8b4691f-bbde-48be-a1b8-7b028e833f06)

![image](https://github.com/unpoller/unpoller/assets/6013759/3f46eedc-9cbd-4a04-b790-f0cd8ee1533d)

![image](https://github.com/unpoller/unpoller/assets/6013759/ca88f62c-1424-4b16-8ef6-3c04b03f6f85)

Thanks
Lawrence

**Comment by davidnewhall** [comment]
> I assumed/thought that because you created the dashboards that you had a good understanding of the data model and how it all worked.

I haven't been very active on this project for years, and I haven't had to do any influx maintenance for just as long.

**Comment by lslamp** [comment]
@davidnewhall 
you are still a star for keeping it up. It is a great product.

Thank you very much. for your patience as well.
